### ISSUE TITLE
Reduce the number of statuses

### ISSUE THREAD

**Issue by Primetalk** [cotiviti/service-lifecycle-api#4]
The statuses `INITIALIZED` and `CONFIGURED` gives nothing to the management of services. They may be reduced to a single. Also we do not need two methods `initialize` and `configure`. There is no use of a service between `initialize` and `configure`

**Comment by mykelalvis** [comment]
Your comment is noted.  However, these will remain.  While I understand the sentiment of the comment, I fail to see how you can make this statement.  `initialize` may do nothing for anything you do, but it does quite a bit for things that I plan to do (which is why it is present).

**Comment by Primetalk** [comment]
I wonder, what do you plan to do with the service in the state between `initialize` and `configure`? For how long the service is supposed to be in this inconsistent state? Which methods can be called after `initialize`? How can you guarantee that only those methods are called? (Guarantee is not a promise "I won't do it", it's a thing that is constrained by the programming language, and the interface.)

**Comment by mykelalvis** [comment]
Guarantee is, in fact, a promise I won't call them because the code we're using is the thing that is driving service creation.  
The service isn't supposed to be in any sort of inconsistent state for any definable amount of time.  That's not your call.  Our deployers will call them in the order we see fit at the time we see fit.  That time will probably be "immediately one after the other" but might not.  There are no promises other than that we will call them in the order specified in the documentation and that we will check the status between and then the runtime will decide if we proceed.

In initialize, my code will verify my local environment because I'm paranoid.

**Comment by Primetalk** [comment]
"Don't make me trust you" :) When the only guarantee is a promise and some documentation that tends to stale... Then we are in a bad situation.

In a reliable programming environment such promises and protocols are better expressed in the form of interfaces that do not allow incorrect operations.

Why the same checks cannot be made before `initialize+configure` or after? Why in the middle?

**Comment by mykelalvis** [comment]
You're welcome to do whatever you want in whichever of the lifecycle phases.  
It is literally impossible to enforce an order from the outside, but since we wrote the executor and that executor is in code, anyone would be welcome to review it.

Again, your comment is noted.
